### ISSUE TITLE
Finalize manifest format

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/http2-push-manifest#1]
Final format should have `path: type` mappings

```
{
    "/path/to/app.js": "script",
    "/path/to/app.css": "style",
   ...
}
```

Spec: https://w3c.github.io/preload/#developer-server-and-proxy-initiated-fetching

**Comment by ebidel** [comment]
As discussed on GoogleChrome/chromium-dashboard#246 (comment).

AFAIK, this isn't implemented anywhere, but spec'd. Not sure if the browser handles it yet.

Valid types: https://fetch.spec.whatwg.org/#concept-request-type

**Comment by surma** [comment]
I think we should add another layer to support defining the pushes for other documents than `index.html` only. Additionally, weights might also become interesting (even though support is currently rather lacking) Seeing what you proposed, this would end up with something like:

``` JSON
{
  "index.html": [
    {
      "path": "style.css",
      "type": "style",
      "weight": 50
    },
    {
      "path": "main.js",
      "type": "script",
      "weight": 50
    },
    {
      "path": "logo_big.jpg",
      "type": "image",
      "weight": 10
    }
  ],
  "post.html": [
    {
      "path": "style.css",
      "type": "style",
      "weight": 50
    },
    {
      "path": "main.js",
      "type": "script",
      "weight": 50
    },
    {
      "path": "logo_small.jpg",
      "type": "image",
      "weight": 10
    }
  ]
}
```

It feels a little heavy, to be honest, but [pushing mindlessly without weights can be harmful](https://twitter.com/surmair/status/652887078938771456), so we should offer options to the dev to adjust the weights.

**Comment by surma** [comment]
Also, cc @igrigorik for any additional input on this :)

**Comment by ebidel** [comment]
Are SPDY weights still part of the spec? How do they fit in with the preload header?

The current setup can be used with any page, not just index.html. The idea is that users run `http2-push-manifest` for each page they want to push resources to. You could gulp to automate this:

```
http2-push-manifest app index.html -m push_index.json
http2-push-manifest app page1.html -m push_page1.json
http2-push-manifest app page2.html -m push_page2.json
```

   ...

The downside is that it produces a bunch of different files, but it yields a super generic format where resources aren't tied to hardcoded URLs. It's trivial to use this format and load the right manifest for the appropriate handler:

``` python
class Handler(http2push.PushHandler):
  @http2push.push('push_manifest.json')
  def get(self):
    ...
```

**There's no fuss when I rename my html files, update URL rewrites, etc**.

A multiple URL manifest is interesting. Maybe it can be an flag option in the CLI? What do you use for the URL keys? Filepaths don't always map to URLs.

**Comment by surma** [comment]
Weights are definitely a part of the [h2 spec](https://httpwg.github.io/specs/rfc7540.html#rfc.section.5.3.2). As I said, without weights, push can have negative impact. In terms of the preload header: AFAIK is no support (or syntax) for weights just yet, neither in H2O nor in GAE. That’s really just an implementation detail of the reverse proxy, isn’t it?

I could go for individual manifests for different HTML files, as well. You’d probably have some kind of naming convention then. Not sure what is more practical here.

Something I probably should have mentioned: I also have a use-case in mind where static hosters like GCS, S3 or GitHub Pages implement support for these manifests as well.

**Comment by igrigorik** [comment]
+1 to https://github.com/GoogleChrome/http2-push-manifest/issues/1#issuecomment-149935746. My only other thought/suggestion would be to allow for dependencies? E.g...

``` json
{
  "index.html": [
    {
      "path": "style.css",
      "type": "style",
      "weight": 50, 
      "children": [{"path": ...}, ... ]
    },
```

/cc @kazuho any thoughts on this? Have you looked into allowing something similar for H2O push?

**Comment by surma** [comment]
@igrigorik I kind of see the value of defining the entire dependency tree per request URL, but wouldn’t that also be available by moving the children to top-level? Á la

``` JSON
{
  "index.html": [
    {
      "path": "style.css",
      "type": "style",
      "weight": 50
    },
    {
      "path": "main.js",
      "type": "script",
      "weight": 50
    }
  ],
  "style.css": [
    {
      "path": "post.css",
      "type": "style",
      "weight": 50
    },
    {
      "path": "checkmark.svg",
      "type": "image",
      "weight": 50
    },
    {
      "path": "logo_small.jpg",
      "type": "image",
      "weight": 10
    }
  ]
}
```

or is there a semantic difference?

**Comment by igrigorik** [comment]
Ah, I guess that works too. :+1:

**Comment by kazuho** [comment]
@surma @igrigorik 
In case of H2O, priorities of both the pulled and the pushed streams are determined by their content-type.  Pushed streams with their content-types set to _highest_ priorities are sent before anything else (see [file.mime.addtypes](https://h2o.examp1e.net/configure/file_directives.html#file.mime.addtypes)), while other pushed streams are prioritized accordingly to the HTTP/2 spec.  Push can be initiated either by the use of `link` header sent from an application server, or by a mruby script embedded in the server configuration file (see [Mruby directives](https://h2o.examp1e.net/configure/mruby_directives.html#modifying-response)).

Generally speaking, it is not a good idea to use weights only to schedule CSS or JavaScript files, since weight in HTTP/2 is a value used for _distributing_ bandwidth between the streams.   In case of CSS or JavaScript files, what you should do is to assign bandwidth _exclusively_ to those files (which is what the dependency-based prioritization of HTTP/2 is responsible of).

If you use weight-based approach only, it would often be the case that the majority of the bandwidth will be consumed by images, since number of the image files being sent is typically way greater than the number CSS or JavaScript files (note: weight-based prioritization distributes the bandwidth to _every single_ stream based on their weights).

please see http://blog.kazuhooku.com/2015/06/http2-and-h2o-improves-user-experience.html for the comparison of weight-based (Chrome) and dependency-based (Firefox) approaches.

EDIT. Aside from the weights, it would not be difficult to support the manifest format in H2O by writing a mruby script.  I am looking forward to the format getting fixed.

**Comment by x1ddos** [comment]
I don't understand, where's `weight` coming from? [rel=preload spec](https://w3c.github.io/preload/) doesn't have it.

+1 to:

``` json
{
  "/index.html": [
    {"/app.css": "style"},
    {"/app.js": "script"},
    {"/resource": "optional-type"},
    {"/typeless": ""}
  ],
  "/another-page": []
}
```

or 

``` json
{
  "/index.html": [
    {
      "url": "/app.css",
      "type": "style"
    }
  ]
}
```

**Comment by x1ddos** [comment]
I mean, I do get HTTP/2 streams have priorities, but we're talking about a different thing here, specifically `Link: <url>; rel=preload` header, which doesn't.

**Comment by surma** [comment]
Pushing without priorities can have easily have negative impact. So I expect all the h2 reverse proxies are bound to add _something_ to define weights.

Also, I’d like to suggest to have an object for each dependency, as this keeps the format extensible.

**Comment by ebidel** [comment]
@surma open question is _HOW_ a dev sets priorities?

**Comment by surma** [comment]
Totally. I think there’s too little experience just yet. But you could think that (low-res) images get a higher priority than JS to prioritize a complete visual over a functional site.

**Comment by ebidel** [comment]
This all gets tricky with paths/urls/rewriting.

---

**Issue 1**

In the case of the single manifest format proposal, how does the following work?

```
{
  "/index.html": [{
      "url": "/app.css",
      "type": "style"
  }],
  ...
}
```

The constructed URL for app.css becomes `https://example.com/index.html/app.css`, which is not correct. AFAICT, the `link rel=preload URL needs to be a full absolute URL. This is at least what GAE is supporting atm.

---

**Issue 2**

There's also the case of pretty URLs (url rewriting), etc:

```
{
  "/page": [{
      "url": "/app.css",
      "type": "style"
   }],
}
```

produces -> `https://example.com/page/app.css` (which may 404)

I think: 
- handler serves "/page" (when prefixed with the origin, URL is expected to resolve on the server)
- "url" needs to be an URL (when prefixed with the origin, URL is expected to resolve on the server)
- means the two are not necessarily tied together (e.g. `https://example.com/page/app.css` may 404 but https://example.com/app.css will not).

---

**Issue 3**

This manifest generator doesn't know about your server URLs. It works on files. Example: run `http2-push-manifest app filename.html` on app/filename.html. The best you could do is:

```
{
  "filename.html": [{
      "url": "/app.css",
      "type": "style"
   }],
   ...
}
```

which requires fixup from the user to change "filename.html" to an actual URL.

Thoughts?

**Comment by x1ddos** [comment]
I think a library shouldn't do any URL rewriting except for prefixing a resource with scheme://host if missing from the manifest, using in-flight request.

So, following the above thought:
1. The contructed URL for `/app.css` and an in-flight request for `https://example.com` host will be `https://example.com/app.css`.
2. Same as (1)
3. I think a generator should never guess, it becomes too complex. The developer always knows what their app URL will look like. The easiest and safest, IMHO, is to just let the developer decide, e.g. using an additional command line argument, like `--prefix` or `--urlbase`. That's what I opted for in Go version of the generator.

**Comment by x1ddos** [comment]
At the end of the day, if an app routing is too complex, the manifest can always be edited by hand.

**Comment by x1ddos** [comment]
In case you guys really want to dereference URIs, it's all spec'ed anyway. I don't see an issue here.

For instance, in case of `/page` and `/app.css`, it is still `/app.css`. But, `/page/` and `app.css` becomes `/page/app.css`.

**Comment by surma** [comment]
+1 to @crhym3. It’s staight-up spec and I’d also intuitively expect `/app.css` to be absolute and `app.css` to be relative.

The manifest _generator_ is a convenience tool. Complex setups (with URL rewriting and such) will require either a much smarter (and app-specific) tool or a manual manifest.

**Comment by ebidel** [comment]
I think we're all saying the same thing? I want to keep this tool very basic an preserve the drop-in nature of it.  

What this tool outputs will be exactly how the user has written their app. No url rewriting, no guessing, possibly a --prefix/--urlbase...but all these other things can be handle by the consumer of this tool and/or the server using it. That means this will be the output:

```
{
  "filename.html": [{
      "url": "/app.css",
      "type": "style"
   }],
   "filename2.html": [{
      "url": "/path/to/app.js",
      "type": "script"
   }],
   ...
}
```

LG?

**Comment by x1ddos** [comment]
:+1:

**Comment by ebidel** [comment]
Actually, what do we think about making "url" the key. This makes the multi-file manifest a superset of the single use case!

multi-file manifest (assume each in in list pushes its own set of resources):

```
{
  "/index.html": {
    "/style.css": {
      "type": "style",
      "weight": 50
    },
    "/path/to/app.js"; {
      "type": "script",
      "weight": 10
    }
  },
  "/page.html": {
    ...
  }
}
```

single-file manifest (/index.html pushes these):

```
{
  "/style.css": {
    "type": "style",
    "weight": 50
  },
  "/path/to/app.js": {
    "type": "script",
    "weight": 10
  }
}
```

**Comment by surma** [comment]
Uh. Like it. :+1:

**Comment by x1ddos** [comment]
So, what have you guys decided? I personally don't mind either, although a single-file manifest could also look like:

``` json
[
  {
    "url": "/style.css",
    "type": "style",
    "weight": 50
  },
  {
    "url": "/path/to/app.js",
    "type": "script",
    "weight": 10
  }
]
```

for completeness :-p
(also, I still don't understand where you're gonna use `weight` with rel=preload).

**Comment by surma** [comment]
@crhym3 Right now `weight` is not supported by anyone (not even by all the browsers). But I suspect that servers like H2O or nginx are going to come up with something. It’s basically a prediction.

I think having multiple manifest files makes sense esp. if you look at @ebidel API (decorators taking a file name). So I vote for that.

**Comment by x1ddos** [comment]
@surma single-file manifest use case is as valid as multi-file, but I'd like the format to support both in one way or another, which is what the discussion seemed to have been converging on already. 

All I'm asking is what the final format is so that I can update it for http2preload go version.

**Comment by ebidel** [comment]
I prefer https://github.com/GoogleChrome/http2-push-manifest/issues/1#issuecomment-151277393 b/c you can easily look things by key (URL) and/or make modifications.

For that reason, I've started implementing https://github.com/GoogleChrome/http2-push-manifest/issues/1#issuecomment-151277393.

Holler if this is totally dumb.

**Comment by x1ddos** [comment]
Sounds good! I'll do the same :)

**Comment by ebidel** [comment]
Released 1.0.0: https://www.npmjs.com/package/http2-push-manifest

**Comment by surma** [comment]
:clap:

**Comment by surma** [comment]
Release 2.0.0: https://github.com/GoogleChrome/simplehttp2server/releases/tag/2.0.0
