### ISSUE TITLE
Pushing content from a static handler

### ISSUE THREAD

**Issue by JosefJezek** [GoogleChrome/http2-push-manifest#3]
Please add option for generate string for Pushing content from a static handler.

https://github.com/GoogleChrome/http2push-gae#pushing-content-from-a-static-handler

I need for https://github.com/StartPolymer/polymer-starter-kit-plus/issues/18

Thank you

**Comment by ebidel** [comment]
What would you like to see here?

**Comment by JosefJezek** [comment]
I would like this string format `'</js/app.js>; rel=preload; as=script, </css/app.css>; rel=preload; as=style'`

Check out this example https://github.com/GoogleChrome/http2push-gae#pushing-content-from-a-static-handler

Thank you

**Comment by JosefJezek** [comment]
I am using gulp plugin for revision all static files, see https://github.com/smysnk/gulp-rev-all

view-source:https://polymer-starter-kit-plus.appspot.com/

```
favicon.4f9c4f7b.ico
manifest.d04d3fdd.json
images/touch/apple-touch-icon.5653bea1.png
elements/elements.vulcanized.a6a5e859.html
scripts/app.b4c4cb79.js
```

**Comment by JosefJezek** [comment]
Example `http2-push-manifest -f path/to/site/index.html --header header.txt`

`header.txt` contain `</js/app.js>; rel=preload; as=script, </css/app.css>; rel=preload; as=style`

**Comment by ebidel** [comment]
The intention of this tool is that it only deals with one thing: discovering resources in a file generating a manifest for those resources. We could add support for generating a file that produces the `Link:` header, but that gets tricky. For example, server URLs might not map to locations on disk (`/path/to/page.html` may not be `/page` on the server).

WDYT? We also need a gulp plugin for this thing!
