### ISSUE TITLE
The list is basically the same which should be used for service worker cache

### ISSUE THREAD

**Issue by kenchris** [GoogleChrome/http2-push-manifest#5]
So why not allow to output the format that platinum-sw-cache expects as well?

@addyosmani

**Comment by kenchris** [comment]
It is already quite easy to use:

```
20 let Manifest = require('http2-push-manifest/lib/manifest');
21 
22 var DIST = '.';
23 
24 var dist = function(subpath) {
25   return !subpath ? DIST : path.join(DIST, subpath);
26 };
27 
28 gulp.task('cache-config', function(callback) {
29   var dir = dist();
30   var config = {
31     cacheId: packageJson.name || path.basename(__dirname),
32     disabled: false
33   };
34 
35   let f = 'index.html';
36 
37   // Make a path if one wasn't given. e.g. basic.html -> ./basic.html
38   if (f.indexOf(path.sep) === -1) {
39     f = `.${path.sep}${f}`;
40   }
41 
42   let basePath = f.slice(0, f.lastIndexOf(path.sep))
43   let inputPath = f.slice(f.lastIndexOf(path.sep) + 1);
44 
45   let manifest = new Manifest({basePath, inputPath, name: 'cache-config.json'}); 
46   manifest.generate().then(output => {
47     config.precache = output.urls.map((url) => {
48       return url.startsWith('/') ? url.slice(1) : url;
49     });
50     config.precache.push('./');
51 
52     let md5 = crypto.createHash('md5');
53     md5.update(JSON.stringify(config.precache));
54     config.precacheFingerprint = md5.digest('hex');
55 
56     var configPath = path.join(dir, 'cache-config.json');
57     fs.writeFile(configPath, JSON.stringify(config), callback);
58   })
59 });
```

So with small changes this would fit well for usage by the Polymer Starter Kit.

**Comment by x1ddos** [comment]
What happens when you have multiple files? e.g. `/index.html`, `/another.html`, and `/third.html`.

**Comment by kenchris** [comment]
You would have to iterate over a list of these files and join the results. The http2-push-manifest binary does similar (which I didn't do above - but should be a simple change)

**Comment by x1ddos** [comment]
Not sure I understand this issue. Is it about partially merging two independent libraries or aligning the format?

If it's the latter, what happens if either sw-cache or http2-push need to add a new feature touching on file format. The two seem to be quite distant in how they deliver desired functionality, it's just so happens that their file formats are similar today. Doesn't mean it won't change. In fact there's a good chance as both are very young and unpolished techniques.

**Comment by x1ddos** [comment]
In other words: you unlikely would want to push everything you'd like to pre-cache.

**Comment by kenchris** [comment]
OK, the Polymer Starter Kit has some gulp task which allows to generate the cache json file for the platinum-sw polymer element. It is not very smart though and basically relies on you using vulcanize to merge all the polymer elements into one file. Now if you don't want to do that and instead want to use http2 you will most probably use http2-push-manifest to generate the file list. 

That brings the problem that you need to generate the cache list differently which is exactly what http2-push-cache does and it has nice code for finding the list of files (tracking imports etc) in the project which can either be pushed and/or cached.

Of course you don't need to track the same files for push and cache, but the code for tracking the files (through imports) is the same and would be good to reuse. You would probably want both as separate gulp tasks or similar.

**Comment by x1ddos** [comment]
I see the point but your last comment makes me feel like this issue simply belongs to PSK with a title similar to "Improve precache file generation gulp task" and has nothing in common with http2-push-manifest generator except for code pattern re-usage.

What stops you from just using `http2-push-manifest` in PSK as is, and improve on that PSK cache gulp task independently.

**Comment by kenchris** [comment]
Nothing really, I didn't know it was that easy to reuse the code before I tried :)

**Comment by ebidel** [comment]
I think https://github.com/GoogleChrome/http2-push-manifest/issues/5#issuecomment-197419250 is the key point. What you push will almost always be a subset of things things you cache. This makes me believe the tasks in PSK could be updated to consume/modify the format from this script. Keeping the two separate still feels like a good idea.
